spring:
  #静态资源处理
  resources:
    #启动默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存相应时间,单位秒
        max-age: 3600
    chain:
      #资源链启动缓存，默认开启
      cache: true
      #启动资源链，默认禁用
      enabled: true
      #压缩资源(gzip,brotli)解析，默认禁用
      compressed: true
      #启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/
  thymeleaf:
    #关闭缓存
    cache: false
    #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存货最大时间，默认是600000（十分钟）
      idle-timeout: 1800000
      #最大连接数,默认是10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认是1800000（30分钟）
      max-lifetime: 1800000
      #连接超时时间,默认是30000（30秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  devtools:
    restart:
      exclude: resources/**,static/**,public/**,templates/**
  redis:
#    host: 175.178.151.38
    host: 127.0.0.1
    port: 6379
    #默认数据库0
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认是8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接 默认0
        min-idle: 5
        #RabbitMQ
  rabbitmq:
    username: root
    password: root
    host: 175.178.151.38
    port: 5672
    #虚拟主机
    virtual-host: /
    listener:
      simple:
        #消费者的最小数量
        concurrency: 10
        #消费者的最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认是true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认是1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认是10000ms
        max-interval: 10000ms
        #重试的间隔乘数。比如2.0，第一次等10s，第二次等20s，第三次等40s
        multiplier: 1




#Mybatis-Plus配置
mybatis-plus:
  #Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据返回类型的别名（默认别名是类名）
  type-aliases-package: com.yuan.seckill.pojo


#Mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.yuan.seckill.mapper: debug

